Remember loaded `BehaviorTree`s of last session
limbonaut/limboai pull request #225
Opened 2024-09-21 14:54 UTC by ydeltastar

Remember which trees were edited when the editor closed and move all editor data to the default configuration file.

Closes: https://github.com/limbonaut/limboai/issues/221

2024-09-21 18:29 UTC, limbonaut requested changes

2024-09-21 18:29 UTC, limbonaut commented on editor/limbo_ai_editor_plugin.cpp
> +	for (const Ref<BehaviorTree> bt : history) {
Should be used by reference, not copy
`const Ref<BehaviorTree> &bt : history`

2024-09-21 18:29 UTC, limbonaut commented on util/limbo_compat.h
> +#define PROJECT_CONFIG_FILE() GET_PROJECT_SETTINGS_DIR().path_join("editor_layout.cfg")
I would rename this macro to `LAYOUT_CONFIG_FILE()` for clarity.

2024-09-21 19:29 UTC, ydeltastar commented
Reviews applied.

2024-09-22 11:32 UTC, limbonaut commented
Thanks

2024-09-22 11:32 UTC, limbonaut approved these changes

2024-09-22 11:32 UTC, merged